/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: JasperTobias (https://sketchfab.com/JasperTobias)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-earth-ce0cce9b528b47c7984bf0b2b600d705
Title: LowPoly Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.05]} scale={100}>
        <mesh geometry={nodes['URF-Height_watr_0'].geometry} material={materials.watr} />
        <mesh geometry={nodes['URF-Height_Lampd_0'].geometry} material={materials.Lampd} />
        <mesh geometry={nodes['URF-Height_Lampd_Ice_0'].geometry} material={materials.Lampd_Ice} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
